app:
  mysql:
    enabled: true
    url: gomicro:gomicro@(172.16.250.224:3306)/gomicro?charset=utf8&parseTime=true&loc=Asia%2FShanghai
    maxIdleConnection: 100
    maxOpenConnection: 130
    connMaxLifetime: 100